apiVersion: v1
kind: Service
metadata:
  name: svc-deployment_NodePort
  namespace: default
spec:
  selector:
    app: deployment-12.4
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    nodePort: 31150
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: helm-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: helm-chart
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: nginx
      nodePort: 31150
  selector:
    app: helm-chart
